name: Capstone Project Platform GCP Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VM_NAME: vm-platform-seed
      INSTANCE_GROUP: mig-platform
      INSTANCE_TEMPLATE: tmp-vm-platform-seed-v2
      REGION: asia-southeast1
      ZONE: asia-southeast1-a
      USER_NAME: dimanthanipun02
      IMAGE_NAME: vm-platform-seed-boot-image-v2

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3.0.1

      - name: Start the vm-platform-seed
        run: gcloud compute instances start ${{ env.VM_NAME }} --zone=${{ env.ZONE }}

      - name: Connect and Build
        run: >
          gcloud compute ssh ${{ env.USER_NAME }}@${{ env.VM_NAME }} --zone=${{ env.ZONE }}
          --command "cd Capstone-Project-Platform/ && git pull --recurse-submodules && mvn clean package"

      - name: Stop the vm-platform-seed instance
        run: gcloud compute instances stop ${{ env.VM_NAME }} --zone=${{ env.ZONE }}

      - name: Delete the boot disk image
        run: gcloud compute images delete ${{ env.IMAGE_NAME }} --quiet
        continue-on-error: true

      - name: Create a new boot disk image
        run: >
          gcloud compute images create ${{ env.IMAGE_NAME }}
          --source-disk=${{ env.VM_NAME }}
          --source-disk-zone=${{ env.ZONE }}
          --storage-location=${{ env.REGION }}

      - name: Delete old template
        run: gcloud compute instance-templates delete ${{ env.INSTANCE_TEMPLATE }} --quiet
        continue-on-error: true

      - name: Create New Instance Template
        run: |
            gcloud compute instance-templates create ${{ env.INSTANCE_TEMPLATE }} \
              --region=${{ env.REGION }} \
              --image=${{ env.IMAGE_NAME }} \
              --machine-type=e2-medium \
              --metadata=startup-script="#!/bin/bash
                # Java setup
                export SDKMAN_DIR='/home/${{ env.USER_NAME }}/.sdkman'
                [[ -s \"\$SDKMAN_DIR/bin/sdkman-init.sh\" ]] && source \"\$SDKMAN_DIR/bin/sdkman-init.sh\"
            
                cd /home/${{ env.USER_NAME }}/Capstone-Project-Platform/
            
                # Start Config Server
                nohup java -jar ./config-server/target/Config-Server-1.0.0.jar > config.log 2>&1 &
                sleep 60
            
                # Start Service Registry
                nohup java -jar ./service-registry/target/Service-Registry-1.0.0.jar > registry.log 2>&1 &
                sleep 30
            
                # Start API Gateway on Port 7000
                nohup java -jar ./api-gateway/target/Api-Gateway-1.0.0.jar --server.port=7000 > gateway.log 2>&1 &"

      - name: Update the instance group and force recreate
        run: |
            gcloud compute instance-groups managed rolling-action start-update ${{ env.INSTANCE_GROUP }} \
              --version=template=projects/${{ secrets.GCP_PROJECT_ID }}/regions/${{ env.REGION }}/instanceTemplates/${{ env.INSTANCE_TEMPLATE }} \
              --region=${{ env.REGION }} \
              --type=proactive \
              --minimal-action=replace \
              --replacement-method=recreate \
              --max-surge=0 \
              --max-unavailable=3