name: Capstone Project Platform GCP Deployment
on:
  push:


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VM_NAME: vm-platform-seed
      INSTANCE_GROUP: mig-platform
      INSTANCE_TEMPLATE: tmp-vm-platform-seed-v3
      REGION: asia-southeast1
      ZONE: asia-southeast1-a
      USER_NAME: dimanthanipun02
      IMAGE_NAME: vm-platform-seed-boot-image-v2

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Start the Seed VM
        run: gcloud compute instances start ${{ env.VM_NAME }} --zone=${{ env.ZONE }}

      - name: Build Project on Seed VM
        run: |
          gcloud compute ssh ${{ env.USER_NAME }}@${{ env.VM_NAME }} --zone=${{ env.ZONE }} --command "
            cd /home/${{ env.USER_NAME }}/Capstone-Project-Platform/ &&
            git pull --recurse-submodules &&
            source ~/.bashrc &&
            mvn clean package -DskipTests
          "

      - name: Stop the Seed VM
        run: gcloud compute instances stop ${{ env.VM_NAME }} --zone=${{ env.ZONE }}

      - name: Recreate Boot Image
        run: |
          gcloud compute images delete ${{ env.IMAGE_NAME }} --quiet || true
          gcloud compute images create ${{ env.IMAGE_NAME }} \
            --source-disk=${{ env.VM_NAME }} \
            --source-disk-zone=${{ env.ZONE }} \
            --storage-location=${{ env.REGION }}

      - name: Update Managed Instance Group (Rolling Replace)
        run: |
          gcloud compute instance-groups managed rolling-action replace ${{ env.INSTANCE_GROUP }} \
            --region=${{ env.REGION }} \
            --max-unavailable=1 \
            --replacement-method=recreate